### PR TITLE
Created controllers and routes

### PR DESCRIPTION
**Pull request by ParisaKalaki**

### CODE REVIEW

**Comment by Olena-Barabash** [comment]
I'd say it's a good idea to separate calls to DB from controllers.
Are you sure we need to make these calls to DB from controllers?

**Comment by ParisaKalaki** [comment]
yeah actually I searched about it and also checked some examples in GitHub,
most of them placed the CRUD in controller.
https://www.coreycleary.me/why-should-you-separate-controllers-from-services-in-node-rest-apis

**Comment by ParisaKalaki** [comment]
and when the controller gets fat, then some parts of the controller move to
the service folder

**Comment by ParisaKalaki** [comment]
I reopened my PR, this is the last version.

**Comment by Olena-Barabash** [comment]
1. If we use search parameters as I suggested in Teams then maybe it would be better to somehow rename 'getAll'?
2. Is it OK that in 'app/requests/get_one_company.rest' we always get a company with id=1?

**Comment by ParisaKalaki** [comment]
1. If we change getAll body, what does it return? it does not return all
companies?
2. yes that is ok because in the URL we send /companies/1 to see whether it
works on one item or not. you can change the 1 to 5 to check as well.

**Comment by Olena-Barabash** [comment]
1. Yes, it returns either all companies or a list of companies with a given filter (by company type and services).

**Comment by ParisaKalaki** [comment]
ok, It's fine, could you change it, and then I can add it to my code?

**Pull request closed without merging**
